/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package mainpackage;

import java.beans.PropertyChangeEvent;
import java.beans.PropertyChangeListener;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.text.DateFormat;
import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.util.Date;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JFrame;
import javax.swing.JOptionPane;

/**
 *
 * @author ammani
 */
public class AjoutDeplacement extends javax.swing.JFrame {

    /**
     * Creates new form AjoutDeplacement
     */
    public AjoutDeplacement() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel0 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jTextField2 = new javax.swing.JTextField();
        jTextField4 = new javax.swing.JTextField();
        jTextField5 = new javax.swing.JTextField();
        jTextField6 = new javax.swing.JTextField();
        jTextField7 = new javax.swing.JTextField();
        jTextField8 = new javax.swing.JTextField();
        jTextField10 = new javax.swing.JTextField();
        jTextField12 = new javax.swing.JTextField();
        jTextField17 = new javax.swing.JTextField();
        jTextField18 = new javax.swing.JTextField();
        jTextField19 = new javax.swing.JTextField();
        jTextField20 = new javax.swing.JTextField();
        jTextField21 = new javax.swing.JTextField();
        jTextField22 = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        jLabel22 = new javax.swing.JLabel();
        jToggleButton1 = new javax.swing.JToggleButton();
        jRadioButton1 = new javax.swing.JRadioButton();
        jRadioButton2 = new javax.swing.JRadioButton();
        jTimeChooser1 = new lu.tudor.santec.jtimechooser.JTimeChooser();
        jTimeChooser2 = new lu.tudor.santec.jtimechooser.JTimeChooser();
        jDateChooser1 = new com.toedter.calendar.JDateChooser();
        jDateChooser2 = new com.toedter.calendar.JDateChooser();
        jTextField11 = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jPanel2.setBackground(new java.awt.Color(204, 204, 255));
        jPanel2.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));

        jLabel0.setFont(new java.awt.Font("Tahoma", 1, 48)); // NOI18N
        jLabel0.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel0.setText("GESTION DES VIHECULES RADEM");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel0, javax.swing.GroupLayout.DEFAULT_SIZE, 960, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(26, Short.MAX_VALUE)
                .addComponent(jLabel0)
                .addGap(25, 25, 25))
        );

        jTextField1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N

        jTextField2.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N

        jTextField4.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N

        jTextField5.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jTextField5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField5ActionPerformed(evt);
            }
        });

        jTextField6.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N

        jTextField7.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jTextField7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField7ActionPerformed(evt);
            }
        });

        jTextField8.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jTextField8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField8ActionPerformed(evt);
            }
        });

        jTextField10.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N

        jTextField12.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jTextField12.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField12ActionPerformed(evt);
            }
        });

        jTextField17.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jTextField17.setToolTipText("");
        jTextField17.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTextField17MouseClicked(evt);
            }
        });
        jTextField17.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField17ActionPerformed(evt);
            }
        });

        jTextField18.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jTextField18.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField18ActionPerformed(evt);
            }
        });

        jTextField19.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N

        jTextField20.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N

        jTextField21.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N

        jTextField22.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/mainpackage/images/Deplacement/full_name.png"))); // NOI18N
        jLabel1.setText("NOM EMPLOYEUR :");

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/mainpackage/images/Deplacement/full_name.png"))); // NOI18N
        jLabel2.setText("PRENOM EMPLOYEUR :");

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/mainpackage/images/Deplacement/vehicule.png"))); // NOI18N
        jLabel3.setText("VEHICULE PERSONNEL :");

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/mainpackage/images/Deplacement/matricul_vehicule.png"))); // NOI18N
        jLabel4.setText("MATRICULE VEHICULE :");

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/mainpackage/images/Deplacement/marque.png"))); // NOI18N
        jLabel5.setText("MARQUE :");

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/mainpackage/images/Deplacement/Nbr_cheveaux.png"))); // NOI18N
        jLabel6.setText("NOMBRE  DE CHEVAUX :");

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/mainpackage/images/Deplacement/puissance.png"))); // NOI18N
        jLabel7.setText("PUISSANCE FISCALE :");

        jLabel8.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/mainpackage/images/Deplacement/ordre.png"))); // NOI18N
        jLabel8.setText("ORDRE :");

        jLabel9.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/mainpackage/images/Deplacement/autoroute.png"))); // NOI18N
        jLabel9.setText("DROIT AUTOROUTE :");

        jLabel10.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel10.setIcon(new javax.swing.ImageIcon(getClass().getResource("/mainpackage/images/Deplacement/indemniteKm.png"))); // NOI18N
        jLabel10.setText("INDEMNITE KM :");

        jLabel11.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel11.setIcon(new javax.swing.ImageIcon(getClass().getResource("/mainpackage/images/Deplacement/destination.png"))); // NOI18N
        jLabel11.setText("DESTINATION :");

        jLabel12.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel12.setIcon(new javax.swing.ImageIcon(getClass().getResource("/mainpackage/images/Deplacement/distance.png"))); // NOI18N
        jLabel12.setText("DISTANCE :");

        jLabel13.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel13.setIcon(new javax.swing.ImageIcon(getClass().getResource("/mainpackage/images/Deplacement/date.png"))); // NOI18N
        jLabel13.setText("DATE DE DEPART :");

        jLabel14.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel14.setIcon(new javax.swing.ImageIcon(getClass().getResource("/mainpackage/images/Deplacement/dateRetour.png"))); // NOI18N
        jLabel14.setText("DATE DE RETOUR :");

        jLabel15.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel15.setIcon(new javax.swing.ImageIcon(getClass().getResource("/mainpackage/images/Deplacement/heure.png"))); // NOI18N
        jLabel15.setText("HEURE DE DEPART :");

        jLabel16.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel16.setIcon(new javax.swing.ImageIcon(getClass().getResource("/mainpackage/images/Deplacement/heureRetour.png"))); // NOI18N
        jLabel16.setText("HEURE DE RETOUR :");

        jLabel17.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel17.setIcon(new javax.swing.ImageIcon(getClass().getResource("/mainpackage/images/Deplacement/nuitPasses.png"))); // NOI18N
        jLabel17.setText("NUIT PASSES");

        jLabel18.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel18.setIcon(new javax.swing.ImageIcon(getClass().getResource("/mainpackage/images/Deplacement/petitDejeuner.png"))); // NOI18N
        jLabel18.setText("NOMBRE DE PETIT DEJEUNER :");

        jLabel19.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel19.setIcon(new javax.swing.ImageIcon(getClass().getResource("/mainpackage/images/Deplacement/dejeuner.png"))); // NOI18N
        jLabel19.setText("NOMBRE DE DEJEUNER :");

        jLabel20.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel20.setIcon(new javax.swing.ImageIcon(getClass().getResource("/mainpackage/images/Deplacement/denir.png"))); // NOI18N
        jLabel20.setText("NOMBRE DE DINER :");

        jLabel21.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel21.setIcon(new javax.swing.ImageIcon(getClass().getResource("/mainpackage/images/Deplacement/total.png"))); // NOI18N
        jLabel21.setText("TOTAL");

        jLabel22.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel22.setIcon(new javax.swing.ImageIcon(getClass().getResource("/mainpackage/images/Deplacement/matricul_agence.png"))); // NOI18N
        jLabel22.setText("MATRICULE AGENCE :");

        jToggleButton1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jToggleButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/mainpackage/images/Deplacement/upload.png"))); // NOI18N
        jToggleButton1.setText("UPLOAD");
        jToggleButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jToggleButton1ActionPerformed(evt);
            }
        });

        jRadioButton1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jRadioButton1.setText("OUI");
        jRadioButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButton1ActionPerformed(evt);
            }
        });

        jRadioButton2.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jRadioButton2.setText("OUI");

        jTimeChooser1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jTimeChooser1.setOpaque(true);
        jTimeChooser1.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                jTimeChooser1MouseMoved(evt);
            }
        });
        jTimeChooser1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTimeChooser1MouseClicked(evt);
            }
        });

        jDateChooser1.setDateFormatString("dd-MM-yyyy");
        try {
            Date date = new SimpleDateFormat("dd-MM-yyyy").parse("10-12-1999");
            jDateChooser1.setDate(date);
        } catch (Exception e) {
            System.out.println(e);
        }
        jDateChooser1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jDateChooser1.addContainerListener(new java.awt.event.ContainerAdapter() {
            public void componentAdded(java.awt.event.ContainerEvent evt) {
                jDateChooser1ComponentAdded(evt);
            }
        });

        jDateChooser2.setToolTipText("");
        jDateChooser2.setDateFormatString("dd-MM-yyyy");
        try {
            Date date = new SimpleDateFormat("dd-MM-yyyy").parse("10-12-1999");
            jDateChooser2.setDate(date);
        } catch (Exception e) {
            System.out.println(e);
        }
        jDateChooser2.getDateEditor().addPropertyChangeListener(
            new PropertyChangeListener() {
                @Override
                public void propertyChange(PropertyChangeEvent e) {
                    if ("date".equals(e.getPropertyName())) {
                        long delta =(jDateChooser2.getDate().getTime()-jDateChooser1.getDate().getTime())/(1000*60*60*24);
                        jTextField17.setText(""+delta);
                        jTextField18.setText(""+(delta+1));
                        jTextField19.setText(""+(delta+1));
                        jTextField20.setText(""+delta);
                    }
                }
            });
            jDateChooser2.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
            jDateChooser2.addContainerListener(new java.awt.event.ContainerAdapter() {
                public void componentAdded(java.awt.event.ContainerEvent evt) {
                    jDateChooser2ComponentAdded(evt);
                }
            });
            jDateChooser2.addAncestorListener(new javax.swing.event.AncestorListener() {
                public void ancestorAdded(javax.swing.event.AncestorEvent evt) {
                    jDateChooser2AncestorAdded(evt);
                }
                public void ancestorMoved(javax.swing.event.AncestorEvent evt) {
                }
                public void ancestorRemoved(javax.swing.event.AncestorEvent evt) {
                }
            });
            jDateChooser2.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
                public void mouseDragged(java.awt.event.MouseEvent evt) {
                    jDateChooser2MouseDragged(evt);
                }
            });
            jDateChooser2.addMouseListener(new java.awt.event.MouseAdapter() {
                public void mouseClicked(java.awt.event.MouseEvent evt) {
                    jDateChooser2MouseClicked(evt);
                }
                public void mouseEntered(java.awt.event.MouseEvent evt) {
                    jDateChooser2MouseEntered(evt);
                }
                public void mouseExited(java.awt.event.MouseEvent evt) {
                    jDateChooser2MouseExited(evt);
                }
                public void mousePressed(java.awt.event.MouseEvent evt) {
                    jDateChooser2MousePressed(evt);
                }
                public void mouseReleased(java.awt.event.MouseEvent evt) {
                    jDateChooser2MouseReleased(evt);
                }
            });
            jDateChooser2.addInputMethodListener(new java.awt.event.InputMethodListener() {
                public void caretPositionChanged(java.awt.event.InputMethodEvent evt) {
                }
                public void inputMethodTextChanged(java.awt.event.InputMethodEvent evt) {
                    jDateChooser2InputMethodTextChanged(evt);
                }
            });
            jDateChooser2.addPropertyChangeListener(new java.beans.PropertyChangeListener() {
                public void propertyChange(java.beans.PropertyChangeEvent evt) {
                    jDateChooser2PropertyChange(evt);
                }
            });
            jDateChooser2.addKeyListener(new java.awt.event.KeyAdapter() {
                public void keyReleased(java.awt.event.KeyEvent evt) {
                    jDateChooser2KeyReleased(evt);
                }
            });
            jDateChooser2.addVetoableChangeListener(new java.beans.VetoableChangeListener() {
                public void vetoableChange(java.beans.PropertyChangeEvent evt)throws java.beans.PropertyVetoException {
                    jDateChooser2VetoableChange(evt);
                }
            });

            jTextField11.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
            jTextField11.addKeyListener(new java.awt.event.KeyAdapter() {
                public void keyReleased(java.awt.event.KeyEvent evt) {
                    jTextField11KeyReleased(evt);
                }
            });

            javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
            jPanel1.setLayout(jPanel1Layout);
            jPanel1Layout.setHorizontalGroup(
                jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel1Layout.createSequentialGroup()
                    .addContainerGap()
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(jPanel1Layout.createSequentialGroup()
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jLabel6)
                                .addComponent(jLabel8)
                                .addComponent(jLabel7)
                                .addComponent(jLabel9)
                                .addComponent(jLabel11)
                                .addComponent(jLabel12)
                                .addComponent(jLabel5)
                                .addComponent(jLabel1)
                                .addComponent(jLabel2)
                                .addComponent(jLabel4)
                                .addComponent(jLabel3)
                                .addComponent(jLabel10))
                            .addGap(18, 18, 18)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(jTextField5)
                                .addComponent(jTextField4)
                                .addComponent(jTextField2)
                                .addComponent(jTextField1)
                                .addComponent(jTextField7)
                                .addComponent(jTextField8)
                                .addComponent(jTextField10)
                                .addComponent(jTextField12)
                                .addComponent(jRadioButton1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jRadioButton2, javax.swing.GroupLayout.DEFAULT_SIZE, 175, Short.MAX_VALUE)
                                .addComponent(jTextField6, javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(jTextField11, javax.swing.GroupLayout.Alignment.TRAILING))
                            .addGap(26, 26, 26)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jLabel14)
                                .addComponent(jLabel13)
                                .addComponent(jLabel15)
                                .addComponent(jLabel16)
                                .addComponent(jLabel17)
                                .addComponent(jLabel18)
                                .addComponent(jLabel19)
                                .addComponent(jLabel20)
                                .addComponent(jLabel21)
                                .addComponent(jLabel22))
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 14, Short.MAX_VALUE)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(jTextField20, javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(jTextField18, javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(jTextField17, javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(jTextField22, javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(jTextField19, javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(jToggleButton1, javax.swing.GroupLayout.DEFAULT_SIZE, 174, Short.MAX_VALUE)
                                .addComponent(jTimeChooser1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jTimeChooser2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jDateChooser2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jDateChooser1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jTextField21))))
                    .addContainerGap())
            );
            jPanel1Layout.setVerticalGroup(
                jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel1Layout.createSequentialGroup()
                    .addGap(21, 21, 21)
                    .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanel1Layout.createSequentialGroup()
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(jTextField1, javax.swing.GroupLayout.DEFAULT_SIZE, 38, Short.MAX_VALUE)
                                .addComponent(jLabel13)
                                .addComponent(jLabel1))
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(jTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jLabel14)
                                .addComponent(jLabel2)))
                        .addGroup(jPanel1Layout.createSequentialGroup()
                            .addGap(3, 3, 3)
                            .addComponent(jDateChooser1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(jDateChooser2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGap(5, 5, 5)))
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanel1Layout.createSequentialGroup()
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(jLabel15)
                                .addComponent(jLabel3)
                                .addComponent(jRadioButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(jTextField4, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jLabel16)
                                .addComponent(jLabel4))
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(jTextField5, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jLabel17)
                                .addComponent(jLabel5))
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(jTextField6, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jLabel18)
                                .addComponent(jLabel6)
                                .addComponent(jTextField18, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(jTextField7, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jLabel19)
                                .addComponent(jLabel7)
                                .addComponent(jTextField19, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(jTextField8, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jLabel20)
                                .addComponent(jLabel8)
                                .addComponent(jTextField20, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(jLabel21)
                                .addComponent(jLabel9)
                                .addComponent(jRadioButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jTextField21, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGroup(jPanel1Layout.createSequentialGroup()
                            .addComponent(jTimeChooser1, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(2, 2, 2)
                            .addComponent(jTimeChooser2, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(jTextField17, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(0, 0, Short.MAX_VALUE)))
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(jTextField10, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jLabel22, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jLabel10)
                                .addComponent(jTextField22, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(jLabel11)
                                .addComponent(jTextField11, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(jTextField12, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jLabel12)))
                        .addComponent(jToggleButton1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addContainerGap())
            );

            jDateChooser2.getAccessibleContext().setAccessibleName("");

            javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
            getContentPane().setLayout(layout);
            layout.setHorizontalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            );
            layout.setVerticalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            );

            pack();
        }// </editor-fold>//GEN-END:initComponents

    private void jTextField8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField8ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField8ActionPerformed

    private void jTextField7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField7ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField7ActionPerformed

    private void jTextField5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField5ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField5ActionPerformed

    private boolean valide_int(String test){
            char[] text = test.toCharArray();
            for (char element:text){
                if(element!='0'&&element!='1'&&element!='2'&&element!='3'&&element!='4'&&element!='5'&&element!='6'&&element!='7'&&element!='8'&&element!='9'){
                    return false;
                }
            }
            return true;
    }
    private boolean valide_real(String test){
            char[] text = test.toCharArray();
            for (char element:text){
                if(element!='.'&&element!='0'&&element!='1'&&element!='2'&&element!='3'&&element!='4'&&element!='5'&&element!='6'&&element!='7'&&element!='8'&&element!='9'){
                    return false;
                }
            }
            return true;
    }
    private boolean valide_date(String test){
            char[] text = test.toCharArray();
            if(text.length!=10||text[2]!='-'||text[5]!='-')return false;
            int day = Character.getNumericValue(text[0])*10+Character.getNumericValue(text[0]);
            int month = Character.getNumericValue(text[3])*10+Character.getNumericValue(text[4]);
            int year = Character.getNumericValue(text[6])*1000+Character.getNumericValue(text[7])*100+Character.getNumericValue(text[8])*10+Character.getNumericValue(text[9]);
            if(day==0||day>31||month==0||month>12||year==0||year>9999)return false;
            return true;
    }
    private String ouiNon(boolean test){
        if(test==true)return "oui";
        return "non";
    }
    private void jToggleButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jToggleButton1ActionPerformed
        // TODO add your handling code here:
        DateFormat date= new SimpleDateFormat("dd-MM-yyyy");
        String NomEmployeur = jTextField1.getText();
        String PrenomEmployeur = jTextField2.getText();
        String VehiculePersonnel = ouiNon(jRadioButton1.isSelected());
        String MatriculeVehicule = jTextField4.getText();
        String Marque = jTextField5.getText();
        String NombreDeChevaux = jTextField6.getText();
        String PuissanceFiscale = jTextField7.getText();
        String Ordre =jTextField8.getText();
        String DroitAutoroute = ouiNon(jRadioButton2.isSelected());
        String IndemniteKm=jTextField10.getText();
        String Destination=jTextField11.getText();
        String Distance=jTextField12.getText();
        String DateDeDepart=date.format(jDateChooser1.getDate());
        String DateDeRetour=date.format(jDateChooser2.getDate());
        String HeureDeDepart=jTimeChooser1.getTimeField().getText();
        String HeureDeRetour=jTimeChooser2.getTimeField().getText();
        String NuitPasses=jTextField17.getText();
        String NombreDePetitDejeuner=jTextField18.getText();
        String NombreDeDejeuner=jTextField19.getText();
        String NombreDeDiner=jTextField20.getText();;
        String Total=jTextField21.getText();;
        String MatriculeAgence=jTextField22.getText();
        

        
        if(NomEmployeur.isEmpty()||PrenomEmployeur.isEmpty()||MatriculeVehicule.isEmpty()||Marque.isEmpty()||NombreDeChevaux.isEmpty()||PuissanceFiscale.isEmpty()||Ordre.isEmpty()||
                IndemniteKm.isEmpty()||Destination.isEmpty()||Distance.isEmpty()||DateDeDepart.isEmpty()||DateDeRetour.isEmpty()||HeureDeDepart.isEmpty()||HeureDeRetour.isEmpty()||
                NuitPasses.isEmpty()||NombreDePetitDejeuner.isEmpty()||NombreDeDejeuner.isEmpty()||NombreDeDiner.isEmpty()||Total.isEmpty()||MatriculeAgence.isEmpty()){
            JFrame frame = new JFrame();
            JOptionPane.showMessageDialog(frame, "un ou plusieurs champs sont vide veuillez remplir tous les champs svp","GESTION DES VEHICULES RADEM",2);
        }
        else{
            if(valide_int(NombreDeChevaux)==false){
                jTextField6.setText("");
                JFrame frame = new JFrame();
                JOptionPane.showMessageDialog(frame, "le champ NOMBRE  DE CHEVEAUX ne doit pas contenir des lettres ou des caractères spéciales, vous devez tapper que des chiffres","GESTION DES VEHICULES RADEM",2);
            }
            else if(valide_int(Ordre)==false){
                jTextField8.setText("");
                JFrame frame = new JFrame();
                JOptionPane.showMessageDialog(frame, "le champ ORDRE ne doit pas contenir des lettres ou des caractères spéciales, vous devez tapper que des chiffres","GESTION DES VEHICULES RADEM",2);
            }
            else if(valide_real(IndemniteKm)==false){
                jTextField10.setText("");
                JFrame frame = new JFrame();
                JOptionPane.showMessageDialog(frame, "le champ INDOMNITE KM ne doit pas contenir des lettres ou des caractères spéciales, vous devez tapper que des nombres réels, exemple : 15.79 ou 17","GESTION DES VEHICULES RADEM",2);
            }
            else if(valide_int(Distance)==false){
                jTextField12.setText("");
                JFrame frame = new JFrame();
                JOptionPane.showMessageDialog(frame, "le champ DISTANCE ne doit pas contenir des lettres ou des caractères spéciales, vous devez tapper que des chiffres","GESTION DES VEHICULES RADEM",2);
            }
            else if(valide_date(DateDeDepart)==false){
                try {
                    Date dt = new SimpleDateFormat("dd-MM-yyyy").parse("10-12-1999");
                    jDateChooser1.setDate(dt);
                } catch (Exception e) {
                    System.out.println(e);
                }
                JFrame frame = new JFrame();
                JOptionPane.showMessageDialog(frame, "le champ DATE DE DEPART doit contenir une forme de date valide, exemple : 10-12-1999","GESTION DES VEHICULES RADEM",2);
            }
            else if(valide_date(DateDeRetour)==false){
                try {
                    Date dt = new SimpleDateFormat("dd-MM-yyyy").parse("10-12-1999");
                    jDateChooser2.setDate(dt);
                } catch (Exception e) {
                    System.out.println(e);
                }
                JFrame frame = new JFrame();
                JOptionPane.showMessageDialog(frame, "le champ DATE DE RETOUR doit contenir une forme de date valide, exemple : 10-12-1999","GESTION DES VEHICULES RADEM",2);
            }
            else if(valide_int(NuitPasses)==false){
                jTextField17.setText("");
                JFrame frame = new JFrame();
                JOptionPane.showMessageDialog(frame, "le champ NUIT PASSES ne doit pas contenir des lettres ou des caractères spéciales, vous devez tapper que des chiffres","GESTION DES VEHICULES RADEM",2);
            }
            else if(valide_int(NombreDePetitDejeuner)==false){
                jTextField18.setText("");
                JFrame frame = new JFrame();
                JOptionPane.showMessageDialog(frame, "le champ NOMBRE DE PETIT DEJEUNER ne doit pas contenir des lettres ou des caractères spéciales, vous devez tapper que des chiffres","GESTION DES VEHICULES RADEM",2);
            }
            else if(valide_int(NombreDeDejeuner)==false){
                jTextField19.setText("");
                JFrame frame = new JFrame();
                JOptionPane.showMessageDialog(frame, "le champ NOMBRE DE DEJEUNER ne doit pas contenir des lettres ou des caractères spéciales, vous devez tapper que des chiffres","GESTION DES VEHICULES RADEM",2);
            }
            else if(valide_int(NombreDeDiner)==false){
                jTextField20.setText("");
                JFrame frame = new JFrame();
                JOptionPane.showMessageDialog(frame, "le champ NOMBRE DE DINER ne doit pas contenir des lettres ou des caractères spéciales, vous devez tapper que des chiffres","GESTION DES VEHICULES RADEM",2);
            }
            else if(valide_real(Total)==false){
                jTextField21.setText("");
                JFrame frame = new JFrame();
                JOptionPane.showMessageDialog(frame, "le champ TOTAL ne doit pas contenir des lettres ou des caractères spéciales, vous devez tapper que des nombres réels, exemple : 15.79 ou 17","GESTION DES VEHICULES RADEM",2);
            }
            else{
                Connection con = null;
                try {
                    con = DriverManager.getConnection(
                            "jdbc:oracle:thin:@localhost:1521:orcl", "c##admin", "admin");
                } catch (SQLException ex) {
                    Logger.getLogger(login.class.getName()).log(Level.SEVERE, null, ex);
                }
        // Create a statement for SQL query
                    Statement stmt = null;
                try {
                    stmt = con.createStatement();
                } catch (SQLException ex) {
                    Logger.getLogger(login.class.getName()).log(Level.SEVERE, null, ex);
                }

        // Execute the query

                ResultSet rsl = null;
                try {
                    String sql = "insert into deplacement values('"+NomEmployeur+"','"+PrenomEmployeur+"','"+VehiculePersonnel+"','"+MatriculeVehicule+"','"+Marque+
                                "',"+NombreDeChevaux+",'"+PuissanceFiscale+"',"+Ordre+",'"+DroitAutoroute+"',"+IndemniteKm+",'"+Destination+"',"+Distance+
                                ",to_date('"+DateDeDepart+" "+HeureDeDepart+"','dd-MM-yyyy hh24:mi:ss'),to_date('"+DateDeRetour+" "+HeureDeRetour+"','dd-MM-yyyy hh24:mi:ss'),'"+
                                HeureDeDepart+"','"+HeureDeRetour+"',"+NuitPasses+","+NombreDePetitDejeuner+","+NombreDeDejeuner+","+NombreDeDiner+","+Total+",'"+MatriculeAgence+"')";
                    stmt.executeQuery(sql);
                } catch (SQLException ex) {
                    Logger.getLogger(Admin.class.getName()).log(Level.SEVERE, null, ex);
                }
                this.setVisible(false);
                JFrame frame = new JFrame();
                JOptionPane.showMessageDialog(frame, "ce deplacement est ajouté avec succès","GESTION DES VEHICULES RADEM",1);
            }
        }
    }//GEN-LAST:event_jToggleButton1ActionPerformed

    private void jTextField12ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField12ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField12ActionPerformed

    private void jTextField18ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField18ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField18ActionPerformed

    private void jRadioButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButton1ActionPerformed
        // TODO add your handling code here:
        if(jRadioButton1.isSelected()){
            Connection con = null;
                try {
                    con = DriverManager.getConnection(
                            "jdbc:oracle:thin:@localhost:1521:orcl", "c##admin", "admin");
                } catch (SQLException ex) {
                    Logger.getLogger(login.class.getName()).log(Level.SEVERE, null, ex);
                }
        // Create a statement for SQL query
                    Statement stmt = null;
                try {
                    stmt = con.createStatement();
                } catch (SQLException ex) {
                    Logger.getLogger(login.class.getName()).log(Level.SEVERE, null, ex);
                }
                ResultSet rsl = null;
                try {
                    String sql = "select * from voiturepersonel where (nomemployeur = '"+jTextField1.getText()+"' AND prenomemployeur = '"+jTextField2.getText()+"' )";
                    rsl=stmt.executeQuery(sql);
                } catch (SQLException ex) {
                    Logger.getLogger(Admin.class.getName()).log(Level.SEVERE, null, ex);
                }
                String matricule=null;
                String marque=null;
                String nbrchevaux=null;
                String puissance=null;
                int i=0;
                try {
                    while(rsl.next()){
                        matricule= rsl.getString("matricul");
                        marque=rsl.getString("marque");
                        nbrchevaux=rsl.getString("nbrchevaux");
                        puissance=rsl.getString("puissancefiscal");
                        i++;
                    }
                } catch (SQLException ex) {
                    Logger.getLogger(AjoutDeplacement.class.getName()).log(Level.SEVERE, null, ex);
                }
                if(i!=0){
                    jTextField4.setText(matricule);
                    jTextField5.setText(marque);
                    jTextField6.setText(nbrchevaux);
                    jTextField7.setText(puissance);
                }
            
        }
        else{
            
        }
    }//GEN-LAST:event_jRadioButton1ActionPerformed

    private void jDateChooser2InputMethodTextChanged(java.awt.event.InputMethodEvent evt) {//GEN-FIRST:event_jDateChooser2InputMethodTextChanged
        // TODO add your handling code here:
    }//GEN-LAST:event_jDateChooser2InputMethodTextChanged

    private void jDateChooser2ComponentAdded(java.awt.event.ContainerEvent evt) {//GEN-FIRST:event_jDateChooser2ComponentAdded
        // TODO add your handling code here:
    }//GEN-LAST:event_jDateChooser2ComponentAdded

    private void jDateChooser1ComponentAdded(java.awt.event.ContainerEvent evt) {//GEN-FIRST:event_jDateChooser1ComponentAdded
        // TODO add your handling code here:
    }//GEN-LAST:event_jDateChooser1ComponentAdded

    private void jTimeChooser1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTimeChooser1MouseClicked
        // TODO add your handling code here:
        System.out.println("the time is : "+jDateChooser1.getDate());
    }//GEN-LAST:event_jTimeChooser1MouseClicked

    private void jTextField17ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField17ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField17ActionPerformed

    private void jTextField17MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTextField17MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField17MouseClicked

    private void jTimeChooser1MouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTimeChooser1MouseMoved
        // TODO add your handling code here:
    }//GEN-LAST:event_jTimeChooser1MouseMoved

    private void jDateChooser2MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jDateChooser2MousePressed
        // TODO add your handling code here:
    }//GEN-LAST:event_jDateChooser2MousePressed

    private void jDateChooser2MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jDateChooser2MouseExited
        // TODO add your handling code here:
    }//GEN-LAST:event_jDateChooser2MouseExited

    private void jDateChooser2MouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jDateChooser2MouseReleased
        // TODO add your handling code here:
    }//GEN-LAST:event_jDateChooser2MouseReleased

    private void jDateChooser2MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jDateChooser2MouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_jDateChooser2MouseEntered

    private void jDateChooser2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jDateChooser2MouseClicked
        // TODO add your handling code here:
        
    }//GEN-LAST:event_jDateChooser2MouseClicked

    private void jDateChooser2MouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jDateChooser2MouseDragged
        // TODO add your handling code here:
        
    }//GEN-LAST:event_jDateChooser2MouseDragged

    private void jDateChooser2VetoableChange(java.beans.PropertyChangeEvent evt)throws java.beans.PropertyVetoException {//GEN-FIRST:event_jDateChooser2VetoableChange
        // TODO add your handling code here:
    }//GEN-LAST:event_jDateChooser2VetoableChange

    private void jDateChooser2PropertyChange(java.beans.PropertyChangeEvent evt) {//GEN-FIRST:event_jDateChooser2PropertyChange
        // TODO add your handling code here:
    }//GEN-LAST:event_jDateChooser2PropertyChange

    private void jDateChooser2AncestorAdded(javax.swing.event.AncestorEvent evt) {//GEN-FIRST:event_jDateChooser2AncestorAdded
        // TODO add your handling code here:
    }//GEN-LAST:event_jDateChooser2AncestorAdded

    private void jDateChooser2KeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jDateChooser2KeyReleased
        // TODO add your handling code here:
        
        System.out.println("the time is : "+jDateChooser1.getDate());
    }//GEN-LAST:event_jDateChooser2KeyReleased

    private void jTextField11KeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextField11KeyReleased
        // TODO add your handling code here:
        String destination = jTextField11.getText();
        try {
            Class.forName("oracle.jdbc.driver.OracleDriver");
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(login.class.getName()).log(Level.SEVERE, null, ex);
        }
// Create a connection
            Connection con = null;
        try {
            con = DriverManager.getConnection(
                    "jdbc:oracle:thin:@localhost:1521:orcl", "c##admin", "admin");
        } catch (SQLException ex) {
            Logger.getLogger(login.class.getName()).log(Level.SEVERE, null, ex);
        }
// Create a statement for SQL query
            Statement stmt = null;
        try {
            stmt = con.createStatement();
        } catch (SQLException ex) {
            Logger.getLogger(login.class.getName()).log(Level.SEVERE, null, ex);
        }

// Execute the query
            
            ResultSet rsl = null;
        try {
            rsl = stmt.executeQuery("select * from ville");
        } catch (SQLException ex) {
            Logger.getLogger(login.class.getName()).log(Level.SEVERE, null, ex);
        }
        try {
            while(rsl.next()){
                String dest=rsl.getString("ville");
                if(destination.equals(dest)){
                    jTextField12.setText(rsl.getString("distance"));
                    //break;
                }
            }
        } catch (SQLException ex) {
            Logger.getLogger(login.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_jTextField11KeyReleased

    
    /**
     * @param args the command line arguments
     */
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private com.toedter.calendar.JDateChooser jDateChooser1;
    private com.toedter.calendar.JDateChooser jDateChooser2;
    private javax.swing.JLabel jLabel0;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JRadioButton jRadioButton1;
    private javax.swing.JRadioButton jRadioButton2;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField10;
    private javax.swing.JTextField jTextField11;
    private javax.swing.JTextField jTextField12;
    private javax.swing.JTextField jTextField17;
    private javax.swing.JTextField jTextField18;
    private javax.swing.JTextField jTextField19;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JTextField jTextField20;
    private javax.swing.JTextField jTextField21;
    private javax.swing.JTextField jTextField22;
    private javax.swing.JTextField jTextField4;
    private javax.swing.JTextField jTextField5;
    private javax.swing.JTextField jTextField6;
    private javax.swing.JTextField jTextField7;
    private javax.swing.JTextField jTextField8;
    private lu.tudor.santec.jtimechooser.JTimeChooser jTimeChooser1;
    private lu.tudor.santec.jtimechooser.JTimeChooser jTimeChooser2;
    private javax.swing.JToggleButton jToggleButton1;
    // End of variables declaration//GEN-END:variables
}
