/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package mainpackage;

import java.awt.Font;
import java.awt.print.PrinterException;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableModel;

/**
 *
 * @author ammani
 */
public class Consulter extends javax.swing.JFrame {

    /**
     * Creates new form Consulter
     */
    public Consulter() {
        initComponents();
        Connection con = null;
        try {
            con = DriverManager.getConnection(
                    "jdbc:oracle:thin:@localhost:1521:orcl", "c##admin", "admin");
        } catch (SQLException ex) {
            Logger.getLogger(login.class.getName()).log(Level.SEVERE, null, ex);
        }
// Create a statement for SQL query
            Statement stmt = null;
        try {
            stmt = con.createStatement();
        } catch (SQLException ex) {
            Logger.getLogger(login.class.getName()).log(Level.SEVERE, null, ex);
        }

// Execute the query
            
            ResultSet rsl = null;
        try {   
            rsl = stmt.executeQuery("select * from deplacement order by datededepart");
        } catch (SQLException ex) {
            Logger.getLogger(login.class.getName()).log(Level.SEVERE, null, ex);
        }
        try {
            while(rsl.next()){
                DefaultTableModel model = (DefaultTableModel) jTable1.getModel();
                model.addRow(new Object[]{rsl.getString("NOMEMPLOYEUR"),rsl.getString("PRENOMEMPLOYEUR"),rsl.getString("VEHICULEPERSONNEL"),rsl.getString("MATRICULEVEHICULE"),rsl.getString("MARQUE"),rsl.getString("NOMBREDECHEVAUX"),rsl.getString("PUISSANCEFISCALE"),rsl.getString("ORDRE"),rsl.getString("DROITAUTOROUT"),rsl.getString("INDEMNITEKM"),rsl.getString("DESTINATION"),rsl.getString("DISTANCE"),rsl.getString("DATEDEDEPART"),rsl.getString("DATEDERETOUR"),rsl.getString("HEUREDEDEPART"),rsl.getString("HEUREDERETOUR"),rsl.getString("NUITPASSES"),rsl.getString("NOMBREPETITDEJEUNER"),rsl.getString("NOMBREDEJEUNER"),rsl.getString("NOMBREDINER"),rsl.getString("TOTAL"),rsl.getString("MATRICULAGENCE"),});
            }
        } catch (SQLException ex) {
            Logger.getLogger(login.class.getName()).log(Level.SEVERE, null, ex);
        }
            
       
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        jButton3 = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(1200, 700));

        jPanel1.setMinimumSize(new java.awt.Dimension(1200, 700));
        jPanel1.setPreferredSize(new java.awt.Dimension(1200, 700));

        jPanel2.setBackground(new java.awt.Color(204, 204, 255));
        jPanel2.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 48)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("GESTION DES VIHECULES RADEM");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(175, 175, 175)
                .addComponent(jLabel1)
                .addContainerGap(196, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addComponent(jLabel1)
                .addContainerGap(26, Short.MAX_VALUE))
        );

        jTextField1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jTextField1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField1ActionPerformed(evt);
            }
        });

        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/mainpackage/images/loupe.png"))); // NOI18N
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jButton2.setText("Reset");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jTextArea1.setColumns(20);
        jTextArea1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jTextArea1.setRows(5);
        jScrollPane2.setViewportView(jTextArea1);

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 306, Short.MAX_VALUE)
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane2)
        );

        jButton3.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jButton3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/mainpackage/images/print.png"))); // NOI18N
        jButton3.setText("Imprimer");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        jTable1.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "NomEmployeur", "PrenomEmplyeur", "VehiculePersonnel", "MatriculeVehicule", "Marque", "NombreDeCheveaux", "PuissanceFiscale", "Ordre", "DroitAutorout", "IndemniteKm", "Destination", "Distance", "DateDeDepart", "DateDeRetour", "HeureDeDepart", "HeureDeRetour", "NuitPasses", "NombreDePetitDejeuner", "NombreDeDejeuner", "NombreDeDiner", "Total", "MatriculeAgent"
            }
        ));
        jTable1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTable1MouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jTable1);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jScrollPane1)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 239, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 171, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jButton3)))))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jTextField1)
                            .addComponent(jButton1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 491, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jTextField1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField1ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        try {
            // TODO add your handling code here:
            jTextArea1.print();
        } catch (PrinterException ex) {
            Logger.getLogger(Consulter.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        DefaultTableModel model = (DefaultTableModel) jTable1.getModel();
        String text = jTextField1.getText();
        if(text.isEmpty()){
            JFrame frame = new JFrame();
            JOptionPane.showMessageDialog(frame, "le champ est vide veuillez tapper un nom, un prenom, une ville ou une date pour chercher les données correspondantes","GESTION DES VEHICULES RADEM",2);
        }
        else{
            int Nbr =model.getRowCount();
            for(int i= Nbr-1; i>=0; i--)model.removeRow(i);
            Connection con = null;
            try {
                con = DriverManager.getConnection(
                        "jdbc:oracle:thin:@localhost:1521:orcl", "c##admin", "admin");
            } catch (SQLException ex) {
                Logger.getLogger(login.class.getName()).log(Level.SEVERE, null, ex);
            }
    // Create a statement for SQL query
                Statement stmt = null;
            try {
                stmt = con.createStatement();
            } catch (SQLException ex) {
                Logger.getLogger(login.class.getName()).log(Level.SEVERE, null, ex);
            }

    // Execute the query

            ResultSet rsl = null;
            String sql;
            if(text.contains("0")||text.contains("1")||text.contains("2")||text.contains("3")||text.contains("4")||text.contains("5")||text.contains("7")||text.contains("8")||text.contains("9")){
                sql="select * from deplacement where ( (datededepart between to_date('"+text+"','dd-MM-yyyy') and to_date('"+text+" 23:59:59','dd-MM-yyyy HH24:MI:SS')) OR (datederetour between to_date('"+text+"','dd-MM-yyyy') and to_date('"+text+" 23:59:59','dd-MM-yyyy HH24:MI:SS'))) order by datededepart";
            }
            else{
                sql =  "select * from deplacement where ( nomemployeur = '"+text+"' OR prenomemployeur = '"+ text+"' OR destination = '"+text+"') order by datededepart";
            }
            try {
                rsl = stmt.executeQuery(sql);
            } catch (SQLException ex) {
                Logger.getLogger(login.class.getName()).log(Level.SEVERE, null, ex);
            }
            DefaultTableModel model1 = (DefaultTableModel) jTable1.getModel();
            try {
                while(rsl.next()){

                    model1.addRow(new Object[]{rsl.getString("NOMEMPLOYEUR"),rsl.getString("PRENOMEMPLOYEUR"),rsl.getString("VEHICULEPERSONNEL"),rsl.getString("MATRICULEVEHICULE"),rsl.getString("MARQUE"),rsl.getString("NOMBREDECHEVAUX"),rsl.getString("PUISSANCEFISCALE"),rsl.getString("ORDRE"),rsl.getString("DROITAUTOROUT"),rsl.getString("INDEMNITEKM"),rsl.getString("DESTINATION"),rsl.getString("DISTANCE"),rsl.getString("DATEDEDEPART"),rsl.getString("DATEDERETOUR"),rsl.getString("HEUREDEDEPART"),rsl.getString("HEUREDERETOUR"),rsl.getString("NUITPASSES"),rsl.getString("NOMBREPETITDEJEUNER"),rsl.getString("NOMBREDEJEUNER"),rsl.getString("NOMBREDINER"),rsl.getString("TOTAL"),rsl.getString("MATRICULAGENCE"),});
                }
            } catch (SQLException ex) {
                Logger.getLogger(login.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
        //model1.
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        DefaultTableModel model = (DefaultTableModel) jTable1.getModel();
        int Nbr =model.getRowCount();
        for(int i= Nbr-1; i>=0; i--)model.removeRow(i);
        Connection con = null;
        try {
            con = DriverManager.getConnection(
                    "jdbc:oracle:thin:@localhost:1521:orcl", "c##admin", "admin");
        } catch (SQLException ex) {
            Logger.getLogger(login.class.getName()).log(Level.SEVERE, null, ex);
        }
// Create a statement for SQL query
            Statement stmt = null;
        try {
            stmt = con.createStatement();
        } catch (SQLException ex) {
            Logger.getLogger(login.class.getName()).log(Level.SEVERE, null, ex);
        }

// Execute the query
            
            ResultSet rsl = null;
        try {
            rsl = stmt.executeQuery("select * from deplacement order by datededepart");
        } catch (SQLException ex) {
            Logger.getLogger(login.class.getName()).log(Level.SEVERE, null, ex);
        }
        try {
            while(rsl.next()){
                DefaultTableModel model2 = (DefaultTableModel) jTable1.getModel();
                model2.addRow(new Object[]{rsl.getString("NOMEMPLOYEUR"),rsl.getString("PRENOMEMPLOYEUR"),rsl.getString("VEHICULEPERSONNEL"),rsl.getString("MATRICULEVEHICULE"),rsl.getString("MARQUE"),rsl.getString("NOMBREDECHEVAUX"),rsl.getString("PUISSANCEFISCALE"),rsl.getString("ORDRE"),rsl.getString("DROITAUTOROUT"),rsl.getString("INDEMNITEKM"),rsl.getString("DESTINATION"),rsl.getString("DISTANCE"),rsl.getString("DATEDEDEPART"),rsl.getString("DATEDERETOUR"),rsl.getString("HEUREDEDEPART"),rsl.getString("HEUREDERETOUR"),rsl.getString("NUITPASSES"),rsl.getString("NOMBREPETITDEJEUNER"),rsl.getString("NOMBREDEJEUNER"),rsl.getString("NOMBREDINER"),rsl.getString("TOTAL"),rsl.getString("MATRICULAGENCE"),});
            }
        } catch (SQLException ex) {
            Logger.getLogger(login.class.getName()).log(Level.SEVERE, null, ex);
        }
        jTextArea1.setText("");
        jTextField1.setText("");
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jTable1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable1MouseClicked
        // TODO add your handling code here:
        int j=jTable1.getSelectedRow();
        String[] str = {"NOM EMPLOYEUR : \t","PRENOM EMPLOYEUR : ","VEHICULE PERSONNEL : ","MATRICULE VEHICULE : ","MARQUE : \t\t","NOMBRE DE CHEVEAUX : ","PUISSANCE FISCALE : \t","ORDRE : \t\t","DROIT AUTUROUT : \t","INDEMNITE KM : \t","DESTINATION : \t","DISTANCE : \t","DATE DE DEPART : \t      ","DATE DE RETOUR : \t    ","HEURE DE DEPART : \t","HEURE DE RETOUR : \t","NUIT PASSES : \t","NOMBRE DE PETITDE JEUNER : ","NOMBRE DE DEJEUNER : ","NOMBRE DE DINER : \t","TOTAL : \t\t","MATRICULE AGENCE : \t"};
        TableModel model = jTable1.getModel();
        jTextArea1.setText("\t        RADEM\n                  GESTION DES VEHICULES\n        ............................................................\n\n");
        for(int i=0;i<22;i++)jTextArea1.append(str[i]+"\t"+model.getValueAt(j, i).toString()+"\n");
    }//GEN-LAST:event_jTable1MouseClicked

    /**
     * @param args the command line arguments
     */
   

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable jTable1;
    private javax.swing.JTextArea jTextArea1;
    private javax.swing.JTextField jTextField1;
    // End of variables declaration//GEN-END:variables
}
